spring:
  application:
    name: Eccomerce
  profiles.active : dev
server:
  port: ${SERVER_PORT:8081}
storage:
  #Directorio local, en donde se van a almacenar las imagenes enviadas de los productos
  upload-dir: uploads/productos
  #Url que va a regresar las imagenes de los productos
  upload-url: /uploads/productos
